# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  checkAndBuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: setup yarn
      run: yarn

    - name: linter
      run: yarn lint
 
    - name: build ts files
      run: yarn build
      
    - name: Archive builded js
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 1
          
  dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - name: Download builded app
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fanfouette-bot:$(date +%s)
    - name: Check image
      run: docker images

